# Generated by Django 5.1.4 on 2025-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
